repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 8fe62d14e0b4d7d845a7022c5c2c3ae41bdd3f26  # frozen: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml

ci:
  autoupdate_schedule: quarterly
