language:
  - objective-c

env:
  global: LATEST_TAG=1
  matrix:
    - VERSION=2.7.8
    - VERSION=3.2.5
    - VERSION=3.3.5
    - VERSION=3.4.1

install:
    - source run_install.sh
    - get_python_environment macpython $VERSION venv
    - pip install delocate
    - cd Pillow
    - if [ -n "$LATEST_TAG" ]; then
      git fetch ;
      git fetch --tags ;
      git checkout `../terryfy/git-closest-tag origin/master` ;
      fi
    - python setup.py bdist_wheel
    - delocate-wheel dist/*.whl
    - rename_wheels dist/*.whl
    - pip install dist/*.whl
    - cd ..

script:
    - cd Pillow
    - python selftest.py --installed
    - pip install nose
    - export NOSE_PROCESS_TIMEOUT=600
    - export NOSE_PROCESSES=-1
    - if [ -f test-installed.py ]; then
      python test-installed.py ;
      else
      python Tests/run.py --installed ;
      fi
    - cd ..

before_deploy: cd Pillow/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: ZcwPFUNQlkSXqy7QRbgJsDwK0feE5ju3ISEbYcjl+zG/C8h/vZVOJpoG4PaeOrTRb2k4VaG/zPM4mN1JJKo4qR4c4X4hHY+sPldiD86ubT0tOPD6Mrm9xgu3KBOIg7OO5uiS6VppGkS/G/zfmMiFl97nxfwp9ecsXdKRieiw2kI=
  region: ORD
  container: wheels
  skip_cleanup: true
