env:
  global:
      - REPO_DIR=Pillow
      - BUILD_COMMIT=HEAD
      - PLAT=aarch64
      - TEST_DEPENDS="pytest-timeout"

language: python
# Default Python version is usually 3.6
python: "3.11"
dist: focal
services: docker

jobs:
  include:
    - name: "3.8 Focal manylinux2014 aarch64"
      os: linux
      arch: arm64
      env:
        - MB_ML_VER=2014
        - MB_PYTHON_VERSION=3.8
    - name: "3.8 Focal manylinux_2_28 aarch64"
      os: linux
      arch: arm64
      env:
        - MB_ML_VER="_2_28"
        - MB_PYTHON_VERSION=3.8
    - name: "3.8 musllinux_1_1 aarch64"
      os: linux
      arch: arm64
      env:
        - MB_ML_VER="_1_1"
        - MB_ML_LIBC="musllinux"
        - MB_PYTHON_VERSION=3.8
    - name: "3.9 Focal manylinux2014 aarch64"
      os: linux
      arch: arm64
      env:
        - MB_ML_VER=2014
        - MB_PYTHON_VERSION=3.9
    - name: "3.9 Focal manylinux_2_28 aarch64"
      os: linux
      arch: arm64
      env:
        - MB_ML_VER="_2_28"
        - MB_PYTHON_VERSION=3.9
    - name: "3.9 musllinux_1_1 aarch64"
      os: linux
      arch: arm64
      env:
        - MB_ML_VER="_1_1"
        - MB_ML_LIBC="musllinux"
        - MB_PYTHON_VERSION=3.9
    - name: "3.10 Focal manylinux2014 aarch64"
      os: linux
      arch: arm64
      env:
        - MB_ML_VER=2014
        - MB_PYTHON_VERSION=3.10
    - name: "3.10 Focal manylinux_2_28 aarch64"
      os: linux
      arch: arm64
      env:
        - MB_ML_VER="_2_28"
        - MB_PYTHON_VERSION=3.10
    - name: "3.10 musllinux_1_1 aarch64"
      os: linux
      arch: arm64
      env:
        - MB_ML_VER="_1_1"
        - MB_ML_LIBC="musllinux"
        - MB_PYTHON_VERSION=3.10
    - name: "3.11 Focal manylinux_2_28 aarch64"
      os: linux
      arch: arm64
      env:
        - MB_ML_VER=2014
        - MB_PYTHON_VERSION=3.11
    - name: "3.11 Focal manylinux_2_28 aarch64"
      os: linux
      arch: arm64
      env:
        - MB_ML_VER="_2_28"
        - MB_PYTHON_VERSION=3.11
    - name: "3.11 musllinux_1_1 aarch64"
      os: linux
      arch: arm64
      env:
        - MB_ML_VER="_1_1"
        - MB_ML_LIBC="musllinux"
        - MB_PYTHON_VERSION=3.11
    - name: "3.12 Focal manylinux_2_28 aarch64"
      os: linux
      arch: arm64
      env:
        - MB_ML_VER=2014
        - MB_PYTHON_VERSION=3.12
    - name: "3.12 Focal manylinux_2_28 aarch64"
      os: linux
      arch: arm64
      env:
        - MB_ML_VER="_2_28"
        - MB_PYTHON_VERSION=3.12
    - name: "3.12 musllinux_1_1 aarch64"
      os: linux
      arch: arm64
      env:
        - MB_ML_VER="_1_1"
        - MB_ML_LIBC="musllinux"
        - MB_PYTHON_VERSION=3.12

before_install:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code
    - libc=${MB_ML_LIBC:-manylinux}
    - docker_image="quay.io/pypa/${MB_ML_LIBC:-manylinux}${MB_ML_VER}_${PLAT}"
    - retry docker pull $docker_image
    - docker run --rm -e BUILD_COMMANDS="build_wheel" -e PYTHON_VERSION="$MB_PYTHON_VERSION" -e MB_PYTHON_VERSION="$MB_PYTHON_VERSION" -e BUILD_COMMIT="HEAD" -e REPO_DIR="$REPO_DIR" -e PLAT="$PLAT" -e MB_ML_VER="$MB_ML_VER" -e MB_ML_LIBC="$libc" -v $PWD:/io -v $HOME:/parent-home $docker_image /io/$MULTIBUILD_DIR/docker_build_wrap.sh
    - ls -l "${TRAVIS_BUILD_DIR}/${WHEEL_SDIR}/"

script:
    - install_run

# Upload wheels to GitHub Releases
deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/${WHEEL_SDIR}/*.whl"
  on:
    repo: python-pillow/pillow-wheels
    tags: true
  skip_cleanup: true
